analysis_archive/stats/analysis.json
docs/nba_api/stats/endpoints/synergyplaytypes.md
docs/nba_api/stats/library/parameters.md
nba_api/stats/endpoints/__init__.py
nba_api/stats/endpoints/synergyplaytypes.py
nba_api/stats/library/parameters.py
tests/stats/deferred_endpoints.py
tools/stats/library/mapping.py

Added SynergyPlayTypes endpoint
1. Added necessary parameter mappings. Also included known patterns for nullable parameters as base valid URL doesn't actually return any useful data. The added parameters patters will be useful for documentation purposes.
2. Added endpoint md, updated parameters.md and analysis.json, added endpoint to tests.

Add SynergyPlayTypes Endpoint

---

tools/stats/endpoint_py_file_generator/generator.py

Fixed a bug in the .py file `generator.py` that wouldn't allow `analyze_endpoints_and_create_files.py` to analyze an endpoint and create a `.py` file for that endpoint in one pass.
Basically the `load_endpoint_file` function is called before `analyze_endpoints_and_create_files.py` generates a file so `load_endpoint_file` always has the `FileNotFoundError`.
https://github.com/swar/nba_api/blob/6acc35c18f4c8e0125d0f89cc2ee226751b80296/tools/stats/endpoint_py_file_generator/generator.py#L88 
I moved that function call into the function body and went ahead and also moved the directory reference into the function as a default argument. Now it's more inline with the endpoint documentation generator. https://github.com/swar/nba_api/blob/6acc35c18f4c8e0125d0f89cc2ee226751b80296/tools/stats/endpoin …

Fixed bug in py file generator

---

docs/nba_api/stats/library/http.md

The documentation for nba_api/stats/library/http.py refers to the file as the other http.py (nba_api/library/http.py)

Fixed description in stats/library/http.md

---

nba_api/stats/library/playbyplayregex.py
tests/stats/library/playbyplay/play_by_play_data.py
tests/stats/library/playbyplay/test_play_by_play_regex.py

PlayByPlayRegEx was expecting 'Full' but received 'Reg.'
known: TRAIL BLAZERS Timeout: Regular (Full 5 Short 0)
Unknown: Magic Timeout: Regular (Reg.4 Short 0)
Expression updated and test added.

Fixed a bug in playbyplay regex

---

nba_api/stats/endpoints/_base.py

Hello @swar ,
Thanks for this amazing repo!
I've figured out a patch for #211 and #98 that is robust to handle `DataSet` objects with an arbitrary number of levels for the column names.
For example, the following command should now work:
```python
from nba_api.stats.endpoints import leaguedashteamshotlocations
raw_data = leaguedashteamshotlocations.LeagueDashTeamShotLocations()
print(raw_data.get_data_frames()[0])
```
When running the tests, I got the same number of failures (113, mostly on test_play_by_play_regex_integration) as before starting my work, so I believe my fix doesn't crash any previously-working features.
Hope this helps, and happy to discuss the changes.
Ethan Baron

Add handling of multiple level column names in DataSets

---

CHANGELOG.MD
src/nba_api/stats/library/playbyplayregex.py
tests/unit/data_playbyplayregex.py

Fixed `playbyplayregex` where the NBA removed a `space` that represented `distance' when `distance` was not included in the made/missed shot.

PlayByPlay Regex Fixes

---

.circleci/config.yml
.gitignore
CHANGELOG.MD
poetry.lock
pyproject.toml

Dropped Support for Python 3.7 due to a security vulnerability in [NumPy v1.21.6](https://security.snyk.io/package/pip/numpy/1.21.6)

Added Snyk Security Scanning. 

---

docs/nba_api/stats/endpoints/commonteamroster.md

order of params doesn't follow call

common team roster, order of params

---

poetry.lock

Reverts swar/nba_api#318 (Last PR prior to build failing)

Revert "Bump certifi from 2022.9.24 to 2022.12.7"

---

docs/nba_api/stats/endpoints/videodetailsasset.md
docs/table_of_contents.md
src/nba_api/stats/endpoints/__init__.py
src/nba_api/stats/endpoints/videodetailsasset.py
tests/integration/deferred_endpoints.py
tools/stats/library/mapping.py

add videodetailsasset endpoint

---

src/nba_api/stats/endpoints/playerindex.py

Fix uncorrect work PlayerIndex endpoint:
- Fix error in name self.nba_response attribute
- Fix error in name data argument for Endpoint.Dataset

Fix wrong name nba_response and DataSet(data=data_set)

---

.devcontainer/devcontainer.json
.devcontainer/postCreateCommand.sh

PYTHON_PATH should be set to the active environment for Poetry. Since this can only be done once the environment is up, changes have been made to the postCreateCommand.sh file to set that during the dev container build.

Dynamically set the PYTHON_PATH env within the Dev Container for Poetry.

---

CHANGELOG.MD
poetry.lock
pyproject.toml

Since Requests 2.3.0, Requests has been leaking Proxy-Authorization headers to destination servers when redirected to an HTTPS endpoint. This is a product of how we use `rebuild_proxies` to reattach the `Proxy-Authorization` header to requests. For HTTP connections sent through the tunnel, the proxy will identify the header in the request itself and remove it prior to forwarding to the destination server. However when sent over HTTPS, the `Proxy-Authorization` header must be sent in the CONNECT request as the proxy has no visibility into the tunneled request. This results in Requests forwarding proxy credentials to the destination server unintentionally, allowing a malicious actor to potentially exfiltrate sensitive information. This issue has been patched in version 2.31.0. …

Resolved CVE-2023-32681

---

src/nba_api/stats/library/eventmsgtype.py

correct ID `18` to `Instant Replay`, instead of `UNKNOWN`
Here is sample for a same event from `playbyplayv2` and `playbyplayv3` which GameID is `0042100212`. According to the comparison, `18` should be `Instant Replay`
* v2 (which eventmsgtype's index is 2)
```
[
'0042100212',
122,
18,
1,
1,
'7:19 PM',
'2:46',
None,
'Instant Replay1st Period (7:19 PM EST)',
None,
'12 - 27',
'15',
0,
0,
None,
None,
None,
None,
None,
0,
0,
None,
None,
None,
None,
None,
0,
0,
None,
None,
None,
None,
None,
0
]
```
* v3
```
{
'actionNumber': 122,
'clock': 'PT02M46.00S',
'period': 1,
'teamId': 0,
'teamTricode': '',
'personId': 0,
'playerName': '',
'playerNameI': '',
'xLegacy': 0,
'yLegacy': 0,
'shotDistance': 0,
'shotResult': '',
'isFieldGoal': 0,
'scoreHome': '27',
'scoreAway': '12',
'pointsTotal': 39, …
```

fix: update 18 as Instant Replay

---

analysis_archive/stats/analysis.json
docs/nba_api/stats/endpoints/iststandings.md
docs/nba_api/stats/library/parameters.md
src/nba_api/stats/endpoints/__init__.py
src/nba_api/stats/endpoints/iststandings.py
src/nba_api/stats/library/http.py
src/nba_api/stats/library/parameters.py
src/nba_api/stats/library/parserv3.py
tests/integration/deferred_endpoints.py
tools/stats/library/mapping.py

@rsforbes 
Hello, I want to add a new endpoint for the In-Season Tournament: ISTStandings
I want to note that the endpoint accepts the Season parameter only in the format \\d{4}-\\d{2}, so I added 20 in front. I think everyone is used to writing only the last two digits of the seasons (23-24).

add ISTStandings endpoint

---

docs/nba_api/live/endpoints/scoreboard.md

minor PR but it looks like there's a mismatch in the [documented property name for the game in `ScoreBoard()`](https://github.com/swar/nba_api/blob/5853b5469c436d9489ef355235209daa3a300bba/docs/nba_api/live/endpoints/scoreboard.md#gamedate-game_date), [and the implementation](https://github.com/swar/nba_api/blob/5853b5469c436d9489ef355235209daa3a300bba/src/nba_api/live/nba/endpoints/scoreboard.py#L107). The docs say `.game_date` but it's implemented as `.score_board_date`. Alternatively, I can instead change what's in https://github.com/swar/nba_api/blob/5853b5469c436d9489ef355235209daa3a300bba/src/nba_api/live/nba/endpoints/scoreboard.py to switch from `scoreboard_game_date` to `game_data` but I figured this change to the docs would be less risky.

update ScoreBoard game_date property name to score_board_date

---

docs/nba_api/stats/endpoints/cumestatsplayer.md
docs/nba_api/stats/library/parameters.md

Updated documentation in cumestatsplayer.md and parameters.md to make the formatting of GameIDs more clear.
Resolves #309

Update GameIDs Pattern Documentation

---

src/nba_api/stats/library/parserv3.py

For example:
endpoint is : `boxscoretraditionalv3`
Game `0012300001`, period `4`, params is: 
``` python
params = {
'game_id': '0012300001',
'range_type': 1,
'start_period': 4,
'end_period': 4,
}
```
NBA official Website response is like this(starters and bench is null):
but nba_api will throw an error:
```
File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/nba_api/stats/endpoints/boxscoretraditionalv3.py", line 141, in __init__
self.get_request()
File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/nba_api/stats/endpoints/boxscoretraditionalv3.py", line 151, in get_request
self.load_response()
File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/nba_api/stats/endpoints/boxscoretraditionalv …
```

Fix BoxScoreTraditionalV3 API Bug(some game stats starters and bench is None, cause 'NoneType' object has no attribute 'values')

---

src/nba_api/library/http.py
tests/unit/test_http.py

* A draft PR that implements injectable requests Sessions as outlined in this issue: https://github.com/swar/nba_api/issues/485

Add requests Session to API calls

---

src/nba_api/stats/endpoints/__init__.py

This was needed for me to `from nba_api.stats.endpoints import ScheduleLeagueV2`

import ScheduleLeagueV2 into __init__.py

---

src/nba_api/stats/endpoints/scoreboardv2.py

fix: handle missing WinProbability data in ScoreboardV2 endpoint
